### ISSUE TITLE
CLI tests stopped working on Travis?

### ISSUE THREAD

**Issue by GitBruno** [mwilliamson/python-mammoth#68]
There seems to be an issue between spur and Travis? CLI tests run fine locally.

```Traceback (most recent call last):
  File "/home/travis/build/ES-Collection/python-mammoth/.tox/py/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/travis/build/ES-Collection/python-mammoth/tests/cli_tests.py", line 66, in style_map_is_used_if_set
    result = _local.run(["mammoth", docx_path, "--style-map", style_map_path])
  File "/home/travis/build/ES-Collection/python-mammoth/.tox/py/site-packages/spur/local.py", line 111, in run
    return self.spawn(*args, **kwargs).wait_for_result()
  File "/home/travis/build/ES-Collection/python-mammoth/.tox/py/site-packages/spur/local.py", line 72, in spawn
    raise NoSuchCommandError(command[0])
NoSuchCommandError: Command not found: mammoth. Check that mammoth is installed and on $PATH```

**Comment by mwilliamson** [comment]
This is due to a change in tox 3.2.0. I've pinned 3.1.3 for now while I investigate a more permanent solution.
