### ISSUE TITLE
Support documents in strict format

### ISSUE THREAD

**Issue by timb07** [mwilliamson/python-mammoth#74]
Hi,

I use Mammoth in an anti-spam application, and have come across a .docx file attached to a spam email that causes Mammoth to throw an exception. I'm using `mammoth.convert_to_html()` in my code, but the same exception is thrown running from the command line:

```py
$ mammoth Paypal_phishing.docx 
Traceback (most recent call last):
  File "/home/tbell/.virtualenvs/python-mammoth/bin/mammoth", line 11, in <module>
    load_entry_point('mammoth', 'console_scripts', 'mammoth')()
  File "/home/tbell/git/python-mammoth/mammoth/cli.py", line 33, in main
    output_format=args.output_format,
  File "/home/tbell/git/python-mammoth/mammoth/__init__.py", line 26, in convert
    return options.read_options(kwargs).bind(lambda convert_options:
  File "/home/tbell/git/python-mammoth/mammoth/results.py", line 15, in bind
    result = func(self.value)
  File "/home/tbell/git/python-mammoth/mammoth/__init__.py", line 27, in <lambda>
    docx.read(fileobj).map(transform_document).bind(lambda document:
  File "/home/tbell/git/python-mammoth/mammoth/docx/__init__.py", line 34, in read
    ]).bind(lambda referents:
  File "/home/tbell/git/python-mammoth/mammoth/results.py", line 15, in bind
    result = func(self.value)
  File "/home/tbell/git/python-mammoth/mammoth/docx/__init__.py", line 35, in <lambda>
    _read_document(zip_file, read_part_with_body, notes=referents[0], comments=referents[1], part_paths=part_paths)
  File "/home/tbell/git/python-mammoth/mammoth/docx/__init__.py", line 132, in _read_document
    comments=comments,
  File "/home/tbell/git/python-mammoth/mammoth/docx/__init__.py", line 172, in read_part
    return _read_entry(zip_file, name, partial(reader, body_reader=body_reader))
  File "/home/tbell/git/python-mammoth/mammoth/docx/__init__.py", line 202, in _read_entry
    return reader(office_xml.read(fileobj))
  File "/home/tbell/git/python-mammoth/mammoth/docx/document_xml.py", line 16, in read_document_xml_element
    return body_reader.read_all(body_element.children) \
AttributeError: 'NoneType' object has no attribute 'children'
```

The input file is attached. (Take care as it appears to be a phishing attack.)

My limited investigation has found that at `docx/document_xml.py:15`, `element.find_child("w:body")` is returning None, despite `word/document.xml` in the unpacked .docx file clearly containing a `<w:body>` element.

[Paypal_phishing.docx](https://github.com/mwilliamson/python-mammoth/files/2863312/Paypal_phishing.docx)

**Comment by mwilliamson** [comment]
Could you check what `xmlns:w` is set to? This might be due to the document using the strict format.

**Comment by timb07** [comment]
It's `xmlns:w="http://purl.oclc.org/ooxml/wordprocessingml/main"`. There's also `w:conformance="strict"`, in case that's relevant.

**Comment by mwilliamson** [comment]
Yup, looks like it's using the strict format.

The equivalent issue for mammoth.js: https://github.com/mwilliamson/mammoth.js/issues/146

**Comment by mwilliamson** [comment]
Support for the strict format has been added in the latest commit. It's possible that are relevant discrepancies between the strict and transitional formats beyond just the namespaces used: if that turns out to the case, feel free to open specific issues.
